MvcLibrary/Models/Entity/Announcement.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public byte AnnouncementId { get; set; }
        public string AnnouncementCategory { get; set; }
        public string AnnouncementContent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}

MvcLibrary/Controllers/AnnouncementController.cs
using MvcLibrary.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcLibrary.Controllers
{
    public class AnnouncementController : Controller
    {
        // GET: Announcement
        DBLibraryEntities entities = new DBLibraryEntities();
        public ActionResult Index()
        {
            var result = entities.Announcement.ToList();
            return View(result);
        }

        [HttpGet]
        public ActionResult AnnouncementAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AnnouncementAdd(Announcement Announcement)
        {
            Announcement.Date = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            entities.Announcement.Add(Announcement);
            entities.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AnnouncementDelete(int id)
        {
            var values = entities.Announcement.Find(id);
            entities.Announcement.Remove(values);
            entities.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AnnouncementUpdate(int id)
        {
            var values = entities.Announcement.Find(id);
          
            return View("AnnouncementUpdate", values);
        }

        [HttpPost]
        public ActionResult AnnouncementUpdate(Announcement Announcement)
        {
            Announcement.Date = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            var values = entities.Announcement.Find(Announcement.AnnouncementId);
            values.AnnouncementCategory = Announcement.AnnouncementCategory;
            values.AnnouncementContent = Announcement.AnnouncementContent;
            entities.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult AnnouncementDetails(int id)
        {
            var values = entities.Announcement.Find(id);
            return View("AnnouncementDetails", values);
        }
    }
}

MvcLibrary/Views/Announcement/AnnouncementAdd.cshtml
@model MvcLibrary.Models.Entity.Announcement
@{
    ViewBag.Title = "AnnouncementAdd";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<script src="~/Scripts/jquery-3.7.0.js"></script>

<br />
<form class="form-group" method="post" id="authorForm">
    <div>
        <label>Kategori Adı</label>
        @Html.TextBoxFor(x => x.AnnouncementCategory, new { @class = "form-control" })
        <br />
        <label>İçerik </label>
        @Html.TextAreaFor(x => x.AnnouncementContent, new { @class = "form-control" })
        <br /> 
       
     

    </div>

    <div>
        <button class="btn btn-outline-success" type="submit" id="btn1">Ekle</button>
    </div>
</form>

<script>
    $("#btn1").click(function (e) {
        e.preventDefault();
        Swal.fire({
            icon: 'success',
            title: 'Başarılı!',
            text: 'Duyuru başarıyla eklendi!'
        }).then(() => {
            $("#authorForm").submit();
        });
    });

</script>

MvcLibrary/Views/Announcement/AnnouncementDetails.cshtml
@model MvcLibrary.Models.Entity.Announcement
@{
    ViewBag.Title = "AnnouncementDetails";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<script src="~/Scripts/jquery-3.7.0.js"></script>

<br />
<form class="form-group" method="post" >
    <div>
        <label>Kategori Adı</label>
        @Html.TextBoxFor(x => x.AnnouncementCategory, new { @class = "form-control", @readonly = "readonly" })

        <br />
        <label>İçerik </label>
        @Html.TextAreaFor(x => x.AnnouncementContent, new { @class = "form-control", @readonly = "readonly" })

        <br />
        <br />
        <label>Zaman </label>
        <span class="form-control">@Model.Date.Value.ToString("dd.MM.yyyy")</span>




        <br />



    </div>

    <div>

    </div>
</form>

MvcLibrary/Views/Announcement/AnnouncementUpdate.cshtml
@model MvcLibrary.Models.Entity.Announcement
@{
    ViewBag.Title = "AnnouncementUpdate";
    Layout = "~/Views/Shared/Layout.cshtml";
}



<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/Scripts/jquery-3.7.0.js"></script>

<br />
@using (Html.BeginForm("AnnouncementUpdate", "Announcement", FormMethod.Post, new { id = "AnnouncementForm" }))
{
    <div>
        @Html.HiddenFor(x => x.AnnouncementId)
        <label>Kategori Adı     <br /></label>
        <br />     <br />
        @Html.TextBoxFor(x => x.AnnouncementCategory, new { @class = "form-control" })
        <br />
        <label>Detaylar </label>
        <br />     <br />
        @Html.TextBoxFor(x => x.AnnouncementContent, new { @class = "form-control" })
        <br />



    </div>

    <div>
        <button class="btn btn-outline-success" type="button" id="btn1">Güncelle</button>
    </div>
}


<script>
    $(document).ready(function () {
        $("#btn1").click(function () {
            Swal.fire({
                title: 'Emin misiniz?',
                text: "Duyuru bilgileri güncellenecek.",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Evet, güncelle!',
                cancelButtonText: 'Vazgeç'
            }).then((result) => {
                if (result.isConfirmed) {
                    $("#AnnouncementForm").submit(); // form gönderilir
                }
            });
        });
    });
</script>

MvcLibrary/Views/Announcement/Index.cshtml
@using MvcLibrary.Models.Entity
@model List<Announcement>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<script src="~/Scripts/jquery-3.7.0.js"></script>
<br />
<h2>Duyurular</h2>


<table class="table table-striped">
    <tr>
        <th>Duyuru No</th>
        <th>Kategori</th>
        <th>İçerik</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detay</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.AnnouncementId</td>
            <td>@item.AnnouncementCategory</td>
            <td>@item.AnnouncementContent</td>
            <td>@item.Date.Value.ToShortDateString()</td>

            <td><a href="/Announcement/AnnouncementDelete/@item.AnnouncementId" id="btn1" class="btn btn-outline-danger btn-delete"> Sil</a></td>
            <td><a href="/Announcement/AnnouncementUpdate/@item.AnnouncementId" class="btn btn-outline-warning"> Güncelle</a></td>
            <td><a href="/Announcement/AnnouncementDetails/@item.AnnouncementId" class="btn btn-outline-info"> Detaylar</a></td>
        </tr>
    }


</table>
<a href="/Announcement/AnnouncementAdd/" class="btn btn-outline-success"> Ekle</a>
<br />

<script>
    $(".btn-delete").click(function (e) {
        e.preventDefault();

        const url = $(this).attr("href");

        Swal.fire({
            title: "Emin misiniz?",
            text: "Bu işlemi geri alamayacaksınız!",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Evet, sil!",
            cancelButtonText: "Hayır"   // İşte burası
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = url;
            }
        });
    });



</script>