MvcLibrary/Controllers/PersonalController.cs
using MvcLibrary.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcLibrary.Controllers
{
    public class PersonalController : Controller
    {
        // GET: Personal
        DBLibraryEntities entities = new DBLibraryEntities();
        public ActionResult Index(string p)
        {
            var values = entities.Personel.ToList();
            if (!string.IsNullOrEmpty(p))
            {
                values = values.Where(x => x.PersonelNameSurname.Contains(p)).ToList();
            }
            return View(values);
        }


        [HttpGet]
        public ActionResult PersonelAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PersonelAdd(Personel Personel)
        {
            if (ModelState.IsValid)
            {
                Personel.Status = true;
                entities.Personel.Add(Personel);
                entities.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("PersonelAdd");
        }

        public ActionResult PersonelDelete(int id)
        {
            var values = entities.Personel.Find(id);
            values.Status = false;
            entities.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult PersonelUpdate(int id)
        {
            ViewBag.status = new List<SelectListItem>
            {
                new SelectListItem{Text = "Aktif",Value="true"},
                new SelectListItem{Text = "Pasif",Value="false"}
            };


            var values = entities.Personel.Find(id);
            return View(values);
        }

        [HttpPost]
        public ActionResult PersonelUpdate(Personel Personel)
        {
            ViewBag.status = new List<SelectListItem>
            {
                new SelectListItem{Text = "Aktif",Value="true"},
                new SelectListItem{Text = "Pasif",Value="false"}
            };
            if (!ModelState.IsValid)
            {
                return View("PersonelUpdate");
            }
            var values = entities.Personel.Find(Personel.PersonelId);
            values.PersonelNameSurname = Personel.PersonelNameSurname;
            values.Status = Personel.Status;
            entities.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcLibrary/Views/Personal/Index.cshtml
@using MvcLibrary.Models.Entity
@model  List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("Index", "Personal", FormMethod.Post))
{
    <div style="margin-bottom:15px; margin-top:15px">
        <p>Aranacak Personel Adını giriniz : </p>@Html.TextBox("p")
        <input type="submit" value="ara" />
    </div>



}

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<script src="~/Scripts/jquery-3.7.0.js"></script>
<br />


<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Personel Adı - Soyadı</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PersonelId</td>
            <td>@item.PersonelNameSurname</td>
            @switch (item.Status)
            {
                case true:
                    <td>Aktif</td>
                    break;
                case false:
                    <td>Pasif</td>
                    break;

            }
            <td><a href="/Personal/PersonelDelete/@item.PersonelId" id="btn1" class="btn btn-outline-danger btn-delete">Personel Sil</a></td>
            <td><a href="/Personal/PersonelUpdate/@item.PersonelId" class="btn btn-outline-warning">Personel Güncelle</a></td>
        </tr>
    }


</table>
<a href="/Personal/PersonelAdd/" class="btn btn-outline-success">Personel Ekle</a>
<br />

<script>
    $(".btn-delete").click(function (e) {
        e.preventDefault();

        const url = $(this).attr("href");

        Swal.fire({
            title: "Emin misiniz?",
            text: "Bu işlemi geri alamayacaksınız!",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Evet, sil!",
            cancelButtonText: "Hayır"   // İşte burası
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = url;
            }
        });
    });



</script>

MvcLibrary/Views/Personal/PersonelAdd.cshtml
@model MvcLibrary.Models.Entity.Personel
@{
    ViewBag.Title = "PersonelAdd";
    Layout = "~/Views/Shared/Layout.cshtml";
}




<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js"></script>



<script src="~/Scripts/jquery-3.7.0.js"></script>

<br />
<form class="form-group" method="post" id="authorForm">
    <div>
        <label>Personel Adı Soyadı</label>
        @Html.TextBoxFor(x => x.PersonelNameSurname, new { @class = "form-control" })
    <br />
        @Html.ValidationMessageFor(x => x.PersonelNameSurname,"",new {@style = "color: red"})
        <br />
    </div>

    <div>
        <br />
        <button class="btn btn-outline-success" type="submit" id="btn1">Ekle</button>
    </div>
</form>

MvcLibrary/Views/Personal/PersonelUpdate.cshtml
@model MvcLibrary.Models.Entity.Personel
@{
    ViewBag.Title = "PersonelUpdate";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js"></script>
<br />
@using (Html.BeginForm("PersonelUpdate", "Personal", FormMethod.Post))
{
    <div>
        @Html.HiddenFor(x => x.PersonelId)
        <label class="form-control">Personel Adı Soyadı</label>
        <br />
        @Html.TextBoxFor(x => x.PersonelNameSurname, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.PersonelNameSurname, "", new { @style = "color: red" })
        <br />
        <br />
        <label class="form-control">Aktif/Pasif</label>
        <br />
        @Html.DropDownListFor(x => x.Status, (IEnumerable<SelectListItem>)ViewBag.status, new { @class = "form-control" })

    </div>
    <br />
    <br />
    <div>
        <button class="btn btn-outline-success" type="submit">Güncelle</button>
    </div>
}